version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install react-router-dom
  build:
    commands:
      - echo Testing...
      # npm run test
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build